name: Deploy API to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Adding Known Hosts
        run: ssh-keyscan -H 137.74.117.241 >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh \
            -o ServerAliveInterval=30 \
            -o ServerAliveCountMax=3 \
            deploy@137.74.117.241 <<EOF
              set -e

              mkdir -p /home/deploy/api
              cd /home/deploy/api

              if [ ! -d .git ]; then
                git clone https://github.com/${{ github.repository }} .
              else
                git fetch origin main
                git reset --hard origin/main
              fi

              echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" > .env
              echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

              docker compose down
              docker compose up -d --build

              docker image prune -f
          EOF

      - name: Verify Deployment
        run: |
          ssh \
            -o ServerAliveInterval=30 \
            -o ServerAliveCountMax=3 \
            deploy@137.74.117.241 <<EOF
              set -e
              cd /home/deploy/api
              docker compose ps
          EOF